### ISSUE TITLE
admin api `/workspaces/{ws_id}/attempts` return huge data

### ISSUE THREAD

**Issue by vm-001** [webhookx-io/webhookx#14]
The `request.body` and `response.body` are returned in the list API `/workspaces/{ws_id}/attempts`. See the example from documentation:

```json
{
  "total": 1,
  "data": [
    {
      "id": "2lbkquwRPXEs6WFJqb8gPoiumgS",
      "event_id": "2lbkqvg8QBjyYuHO1V8f8TThLpv",
      "endpoint_id": "2lbkpcHXI7hpDoP22CP0fZ85zJY",
      "status": "SUCCESSFUL",
      "attempt_number": 1,
      "scheduled_at": 1725456357071,
      "attempted_at": 1725456357583,
      "error_code": null,
      "request": {
        "method": "POST",
        "url": "https://httpbin.org/anything",
        "headers": {
          "Api-Key": "secret",
          "Content-Type": "application/json; charset=utf-8",
          "User-Agent": "WebhookX/"
        },
        "body": "{\"key\": \"value\"}"
      },
      "response": {
        "status": 200,
        "headers": {
          "Access-Control-Allow-Credentials": "true",
          "Access-Control-Allow-Origin": "*",
          "Content-Length": "503",
          "Content-Type": "application/json",
          "Date": "Wed, 04 Sep 2024 13:26:02 GMT",
          "Server": "gunicorn/19.9.0"
        },
        "body": "{\n  \"args\": {}, \n  \"data\": \"{\\\"key\\\": \\\"value\\\"}\", \n  \"files\": {}, \n  \"form\": {}, \n  \"headers\": {\n    \"Accept-Encoding\": \"gzip\", \n    \"Api-Key\": \"secret\", \n    \"Content-Length\": \"16\", \n    \"Content-Type\": \"application/json; charset=utf-8\", \n    \"Host\": \"httpbin.org\", \n    \"User-Agent\": \"WebhookX/\", \n    \"X-Amzn-Trace-Id\": \"Root=1-66d85fe7-618479242937ff9d43b29e47\"\n  }, \n  \"json\": {\n    \"key\": \"value\"\n  }, \n  \"method\": \"POST\", \n  \"origin\": \"155.254.60.32\", \n  \"url\": \"https://httpbin.org/anything\"\n}\n"
      },
      "created_at": 1725456357071,
      "updated_at": 1725456357071
    }
  ]
}
```

Is there an option to control whether to return the `request.body` and `response.body`?

**Comment by cchenggit** [comment]
How about this `attempts` api response attempt without `request` and `response`，and provide a api to query them with `attempt id`. 
let's remove `request` and `response` from `attempt` table, and add a new table to keep them. 

for example:

API: `GET /workspaces/{ws_id}/attempts/{attempt_id}/context` 

Response:

```json
{
 "code":1,
 "data":{
	"id":"2lbkquwRPXEs6WFJqb8gPoiumgS",
	"attempt_id":"2lbkqvg8QBjyYuHO1V8f8TThLpv",
	 "request": {
           ....
         },
        "response": {
         ....
        },
      "created_at": 1725456357071,
      "updated_at": 1725456357071
 }
}
```

**Comment by webhookx-x** [comment]
Adding a new API for the HTTP inspect information seems unnecessary as `GET /workspaces/{ws_id}/attempts/{attempt_id}` can do that.

I prefer to omit `request.headers`, `request.body`, `response.headers`, and `response.body`. and be provided at `GET /workspaces/{ws_id}/attempts/{attempt_id}`.  

Adding a separate table for storing is a good idea. 

@cchenggit Are you interested in picking it up?

1. Add a new entity AttemptDetail (AttemptId, RequestHeader, RequestBody, ResponseHeader, ResponseBody)
2. Fill Attempt.Request and Attempt.Response from AttemptDetailt in API `GET /workspaces/{ws_id}/attempts/{attempt_id}`

**Comment by cchenggit** [comment]
yeah, `GET /workspaces/{ws_id}/attempts/{attempt_id}` would be better.

I'd like to give it a try.
